name: Send Notification Email
on:
  push:
    branches:
      - '**'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Get Branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Send Notification Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.outlook.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Cambios subidos a rama ${{ env.branch_name }}'
          body: 'Un nuevo push se ha realizado en el repositorio en la rama ${{ env.branch_name }}. Please check the details.'
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.SMTP_USERNAME }}